export const TABLES = {
  PEOPLE: 'Users',
  ORGANIZATIONS: 'Companies',
  ORG_MEMBERSHIPS: 'Organization Memberships',
  PERMISSION_PROFILES: 'Permission Profiles',
  RELATIONSHIP_CONTEXTS: 'Relationship Contexts',
  PORTAL_ACCOUNTS: 'Portal Accounts',  // future
  MEETINGS: 'Meetings',                // was: Portal Calendar Events
  NOTES: 'Notes',                      // was: Session Notes
  TASKS: 'Tasks',
  COACH_SESSION: 'Coach Session',
  COACH_PERSON_CONTEXT: 'Coach-Person Context',
} as const

export const FIELDS = {
  RELATIONSHIP_CONTEXTS: {
    PERSON: 'Person',
    LEAD: 'Lead',
    TYPE: 'Relationship Type',
    PERMISSION_LEVEL: 'Permission Level',
    STATUS: 'Status',
    START_DATE: 'Start Date',
  },
  MEETINGS: {
    TITLE: 'Subject',
    START: 'Start Time',
    END: 'End Time',
    PROVIDER_EVENT_ID: 'Provider Event ID',
    ATTENDEES: 'Attendees',
    CALENDAR_OWNER: 'Calendar Owner',
    CLIENT_NAME: 'Client Name',
    REL_CONTEXT_ID: 'Relationship Context ID',
    TIMEZONE: 'Timezone',
    MEETING_STATUS: 'Meeting Status',
    CALENDAR_PROVIDER: 'Calendar Provider',
  },
  NOTES: {
    BODY: 'Content',
    DATE: 'Date',
    CLIENT: 'Client',
    COACH_NAME: 'Coach Name',
    AUTHOR_PERSON: 'Author Person',
    SUBJECT_PERSON: 'Subject Person',
    MEETING: 'Meeting',
    NOTE_TYPE: 'Note Type',
    VISIBILITY: 'Visibility',
  },
  TASKS: {
    TITLE: 'Title',
    STATUS: 'Status',
    DUE_DATE: 'Due Date',
    CLIENT: 'Client',
    NOTES: 'Notes',
    RELATIONSHIP_CONTEXT: 'Relationship Context',
    CREATED_BY_PERSON: 'Created By Person',
    ASSIGNED_TO_PERSON: 'Assigned To Person',
    TASK_TYPE: 'Task Type',
    VISIBILITY: 'Visibility',
  },
  COACH_SESSION: {
    COACH: 'Coach',
    CALENDAR_EVENT: 'Calendar Event',
    FOCAL_PERSON: 'Focal Person',
    SESSION_NOTES: 'Session Notes',
    ACTION_ITEMS: 'Action Items',
    LAST_UPDATED: 'Last Updated',
  },
  USERS: {
    INTERNAL_NOTES: 'Internal Notes',
    TITLE: 'Title',
  },
  COACH_PERSON_CONTEXT: {
    COACH: 'Coach',
    PERSON: 'Person',
    QUICK_NOTES: 'Quick Notes',
    FAMILY_DETAILS: 'Family Details',
    RELATIONSHIP_FLAGS: 'Relationship Flags',
    LAST_UPDATED: 'Last Updated',
  },
} as const
